# Generated by Django 5.0.6 on 2024-07-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_posts', 'Can edit posts')]},
        ),
    ]
